---
# tasks file for install clever-tools on Linux and Unix systems

# This task avoids downloading clever-tools every time
- name: Linux/Unix | Check if clever cloud tools is present with the right version
  ansible.builtin.command: "{{ clever_tools_path }}/clever version"
  register: clever_tools_installed_version
  ignore_errors: true
  changed_when: false
  failed_when: false

- name: Linux/Unix | Download and extract clever-tools
  ansible.builtin.unarchive:
    src: "{{ clever_tools_pkg_url }}"
    dest: "{{ clever_tools_path }}"
    remote_src: true
    extra_opts: ['--strip-components=1']
  when: clever_tools_version not in clever_tools_installed_version.stdout | default('empty')
