---
# tasks file for install clever-tools on Windows system

# This task avoids downloading clever-tools every time
- name: Windows | Check if clever-tools is present with the right version
  ansible.windows.win_command: clever version
  register: clever_tools_installed_version
  ignore_errors: true
  changed_when: false
  failed_when: false

- name: Windows | Download clever-tools
  ansible.windows.win_get_url:
    url: "https://clever-tools.clever-cloud.com/releases/{{ clever_tools_version }}/clever-tools-{{ clever_tools_version }}_win.zip"
    dest: '%TEMP%\clever-tools-{{ clever_tools_version }}_win.zip'
  when: clever_tools_version not in (clever_tools_installed_version.stdout_lines | default(['empty']) | first)

- name: Windows | Create clever-tools folder
  ansible.windows.win_file:
    path: "{{ clever_tools_path }}"
    state: directory

- name: Windows | Install clever-tools
  community.windows.win_unzip:
    src: '%TEMP%\clever-tools-{{ clever_tools_version }}_win.zip'
    dest: "{{ clever_tools_path }}"
  when: clever_tools_version not in (clever_tools_installed_version.stdout_lines | default(['empty']) | first)

- name: Windows | Add clever-tools to PATH
  ansible.windows.win_path:
    elements: "{{ clever_tools_path }}"
